services:
  app-green:
    image: ${DOCKER_IMAGE}
    container_name: green-app
    environment:
      - APP_COLOR=green
      - APP_VERSION=${APP_VERSION:-v1}
      - PORT=3000
    ports:
      - "8082:3000"
    restart: unless-stopped
